### ISSUE TITLE
Install erros - version conflicts

### ISSUE THREAD

**Issue by silveur** [pmaji/crypto-whale-watching-app#116]
Trying to install with python 3.6.0 but got the following error. Modifying the version manually creates a lot more errors...
```
ERROR: Cannot install -r requirements.txt (line 3) and requests==2.21.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested requests==2.21.0
    cbpro 1.1.4 depends on requests==2.13.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
```

**Comment by mifunetoshiro** [comment]
pip install -r /path/to/requirements.txt works perfectly fine...

**Comment by 3raserHead** [comment]
Hi, i have the same problem, getting the following errors when installing via pip install -r
Any suggestions?

Mr-sYns-MacBook-Pro-2:crypto-whale-watching-app-master mrsyn$ pip install -r requirements.txt
Requirement already satisfied: cbpro==1.1.4 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from -r requirements.txt (line 3)) (1.1.4)
Requirement already satisfied: chardet==3.0.4 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from -r requirements.txt (line 5)) (3.0.4)
Requirement already satisfied: pymongo==3.5.1 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from -r requirements.txt (line 28)) (3.5.1)
Requirement already satisfied: retrying==1.3.3 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from -r requirements.txt (line 33)) (1.3.3)
Requirement already satisfied: six==1.10.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from -r requirements.txt (line 34)) (1.10.0)
Requirement already satisfied: websocket-client==0.40.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from -r requirements.txt (line 38)) (0.40.0)
Requirement already satisfied: werkzeug>=0.15.3 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from -r requirements.txt (line 39)) (1.0.1)
Collecting attrs==19.1.0
  Using cached attrs-19.1.0-py2.py3-none-any.whl (35 kB)
Collecting bintrees==2.0.7
  Using cached bintrees-2.0.7.zip (95 kB)
INFO: pip is looking at multiple versions of bintrees to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of attrs to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install cbpro==1.1.4 and requests==2.21.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested requests==2.21.0
    cbpro 1.1.4 depends on requests==2.13.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

**Comment by pmaji** [comment]
Works fine on my end. My advice is that it appears that you're running this outside of starting a fresh virtual environment. Create a separate virtual environment just for this project, spin it up, and install the requirements fresh. That should work np.
