### ISSUE TITLE
No hover text on Plotly lines

### ISSUE THREAD

**Issue by mifunetoshiro** [pmaji/crypto-whale-watching-app#57]
As suggested here https://github.com/pmaji/crypto-whale-watching-app/pull/31#issuecomment-367026912 it'd be great to have a hover text on Plotly lines ("ladder whales") as with the bubbles instead of annotations, but Plotly does not support that. A workaround might be https://stackoverflow.com/questions/46037897/line-hover-text-in-plotly/46039229#46039229

**Comment by theimo1221** [comment]
If #58 get´s pulled this is fixed.
@mifunetoshiro Thanks for suggestion
@pmaji Please merge to main
@CrackLord Please update after merge

**Comment by pmaji** [comment]
I am happy with the final implementation of this. The reason I didn't go this route initially @mifunetoshiro is because either way you have either a user-confusion problem or an object collision problem: either the invisible bubbles are too BIG and end up covering up entire other bubbles making the tool-tip for one or the other useless, or they are too SMALL and end up being impossible to find for users who don't hover over exactly the dead center of the object. Nonetheless, for now it looks ok, and I'm good closing this. @CrackLord feel free to update now that master has been merged.

**Comment by CrackLord** [comment]
> @CrackLord feel free to update now that master has been merged.

Done :)
