### ISSUE TITLE
Some orders not grouping together

### ISSUE THREAD

**Issue by mifunetoshiro** [pmaji/crypto-whale-watching-app#77]
See:
https://i.imgur.com/0UuGiWF.png
https://i.imgur.com/pquAdI3.png

These should all be "ladder whales", 8.000 LTC ladder and 450 BTC ladder, but are 7 and 9 bubbles instead, all for the same amount (1000 LTC and 50 BTC)

**Comment by theimo1221** [comment]
For direct image:
![image](https://user-images.githubusercontent.com/20605452/36680976-97c22708-1b17-11e8-84c5-3ad44e201469.png)
![image](https://user-images.githubusercontent.com/20605452/36680983-a1fbc30a-1b17-11e8-8538-d1cdf231ae2e.png)

They still are grouping but far more on x Axis not in your screenshot.

Those orders are listed at 2 places due to the fact that each unique is bigger than 1% of total volume and additionally as ladder.
But I personally don´t want to take one out since bubble information is better at giving clarity about this is one person while ladder gives better suggestion about hte overall influence.

**Comment by theimo1221** [comment]
ladder are already lines wich makes them kind of hard to handle same as the bubbles...
And making some kind of connection can "mess up" whole view...

**Comment by mifunetoshiro** [comment]
Yes, I know, but I meant connecting the bubbles in the above examples like this: https://i.imgur.com/gWI7uUa.png In this case there would be no need to list it at 2 places (both as bubbles and as a ladder), but just once with connected bubbles. Don't know how hard it would be to change the code and implement this though...

**Comment by theimo1221** [comment]
the ladder behind the bubbles is for a different size....
So the ladder is at complete other side of graph, due to the fact that it´s combined volume is much higher than the bubbles each....

It´s a rare case having both, so making a connection from one side to other side of graph would be awkward...

**Comment by mifunetoshiro** [comment]
No, no, you misunderstood! I know now there is a ladder on the other side of the graph not in the screenshot, and I don't want to connect that ladder with the bubbles on the screenshot, I'm saying it would be nice if the bubbles were connected with a Plotly "lines+markers" mode and only this would be on the graph, no ladder on the other side of the graph.

**Comment by theimo1221** [comment]
Okay but that is totally misleading cause it's on complete wrong x axis value

**Comment by pmaji** [comment]
The lines + markers mode would be a difficult solution to this @mifunetoshiro, even though I see what you are going for. While it might be visually helpful in some instances, it runs counter to the original purpose of the algorithm. Let me try to explain.

The categorical difference between a "ladder price point whale" and a "single price point whale" as I define them in the read me is, yes on one hand, a question of agency--i.e. WHO is behind it. That said, the FUNCTIONAL definition that matters for traders is not WHO is behind it, but what is the probability that it could be used in spoofing / manipulation, which involves the capacity for it to be eaten quickly or pulled. One "rung" on a "ladder" is definitionally different from a single price point because a rung CAN be eaten quickly given its smaller size. As such, it isn't definitionally possible for a large price point (big bubble) to be treated similarly as a rung because it cannot be eaten quickly. As such, I hesitate to do anything that even slightly hints (visually or otherwise) at the fact that a large bubble price points look like rungs on a ladder. I played around with a few visual changes to address your point myself, and I find none of them to be.... improvements, on the status quo. That said, if you have any other ideas (even if it's just scribbles on a paper / arrows drawn on a screenshot) I will consider it and see if it makes sense, but for now I lean towards the status quo.

**Comment by mifunetoshiro** [comment]
> As such, I hesitate to do anything that even slightly hints (visually or otherwise) at the fact that a large bubble price points look like rungs on a ladder.

But that's not what I'm trying to do. A lot of confusion in this thread, maybe I'm confused too xD

I originally opened this thread because I thought there was an issue with grouping some orders, but theimo1221 told me that they are in fact grouped, it's just that I didn't screenshot their ladder:

!(https://i.imgur.com/3pLqvRq.png)

I then thought it's misleading plotting the same order/s twice on the graph, once as bubbles, and once as a ladder, so thought that just plotting it once is enough: plot the bubbles only, but connect them so it's obvious they are part of the same whale and constitute a "ladder."

**Comment by mifunetoshiro** [comment]
See this example: https://i.imgur.com/Vj6lQ6X.png

this order is shown on the graph twice, once as two bubbles, and once as a ladder. My idea is to not plot the ladder as well, because that gives the wrong impression that there are more orders than there really are, but only the two bubbles and connect them with a line (lines+markers mode in Plotly). You know what I mean?

**Comment by theimo1221** [comment]
@mifunetoshiro 
In my opinion both have their right of existency. 
The bubble is important to show it´s one person 
The ladder is important to give a hint some orders might be correlated to each other, resulting in higher total volume than single orders

Things to consider:
1. Filtering out the bubbles if they are part of the ladder is possible but takes a lot of computation
2. Filtering out ladders would be possible with less computation, but wouldn´t allow to see it on first glence.
3. With our description it´s clear that ladders and bubbles have to been seen from different perspective
So having them 2 times is in my opinion no problem at all.

@pmaji What is your oppinion on this?

**Comment by pmaji** [comment]
It's a tough question @mifunetoshiro @theimo1221. I don't believe that by any stretch it is a catastrophic problem, but it IS an interpretability problem. Ideally users should be able to understand the data we're presenting easily without thorough knowledge of the README, and in this case that's kinda hard. 

I think you lay out a good holistic view of the options @theimo1221, and out of them, #2 seems the right way to go, because visually the orders will still look like a ladder, just with added attention drawn to them due their size. I appreciate your guys' thoughts on this; great ideas all around.

**Comment by theimo1221** [comment]
In my opinion having it twice is easier to understand^^
Cause with one glance you can see "Oh, thats a ladder with total volume of xy"
While at the same time beeing able to see "oh there are some big orders"

I added it in #88 with a global Variable de-/ activating it

**Comment by mifunetoshiro** [comment]
Ok, thanks. Would love to see these bubbles connected with a line so it's more obvious they are part of a ladder, but I'll close this issue now.
