### ISSUE TITLE
Bid limit is incorrect

### ISSUE THREAD

**Issue by PlamenHristov** [pmaji/crypto-whale-watching-app#79]
[This line](https://github.com/pmaji/crypto-whale-watching-app/blob/master/app.py#L144) incorrectly takes first_ask, as opposed to first_bid. Additionally, first_bid is never initialized.

**Comment by theimo1221** [comment]
@PlamenHristov  [this line](https://github.com/pmaji/crypto-whale-watching-app/blob/master/app.py#L144) 
`perc_above_first_bid = ((1.0 - range) * first_ask)`

And it´s on purpose, due to a rare error case in which the "first bid" was completly to low, resulting in awkward graphs.

So now we calculate range from same starting point resulting in a total range of 2*unique range instead of before  2*unique range + gap

**Comment by PlamenHristov** [comment]
@theimo122, I see. Sounds good then.
