### ISSUE TITLE
Wrong order sizes listed on graph

### ISSUE THREAD

**Issue by mifunetoshiro** [pmaji/crypto-whale-watching-app#84]
![order size](https://i.imgur.com/OwTTEUN.jpg)

Should be 30, 40, 50, ... 120, 130...

Or is this intentional to not clog the space up?

@pmaji also unrelated, but ladder_tooltip_screenshot.JPG and bubble_tooltip_screenshot.JPG should be updated to show the new info available in the tooltip (and I guess the readme as well).

**Comment by theimo1221** [comment]
As described in read me it's logscale to give better total overview 
Imagine in your screenshot if difference in volume of 10 would always be same width 
You'd have due to that 300 one a very thin spot for each 10 volume resulting in those orders from 10-50 beeing at nearly same place while between 100-180 there would be empty space and between 200-290 again.

But that is General advantage from logscale vs normal in situations like this.

So having a logscale is a huge plus in my opinion

**Comment by theimo1221** [comment]
I maybe misunderstood you 
Regarding naming 80 90 100 200 300 we have no influence as far as I know

So he is doing 10 2 3 4 8 9 100 2 3 4 8 9 1000 2 3 4...

**Comment by mifunetoshiro** [comment]
>  Regarding naming 80 90 100 200 300 we have no influence as far as I know

Oh, ok, I guess I'll close this then
