### ISSUE TITLE
Make hover state stay up until you mouseout

### ISSUE THREAD

**Issue by ccampbell** [pmaji/crypto-whale-watching-app#91]
Right now when you hover over a dot, the tooltip disappears before you have a chance to fully read what it says. It should stay up until you move the mouse off of it.

**Comment by pmaji** [comment]
Hi @ccampbell, I appreciate the feedback. It is actually a refresh question, and not a question of modifying the tool-tip. Every time the tool-tip disappears that is because we are refreshing the background data (so that gives you an idea of the speed of the refresh-rate). The entire reason we implemented a freeze button was to find a workaround for this, so if you want the tool-tips to not freeze, simple click the freeze button. Hope that helps :) 

If for some reason that doesn't make sense, let me know, otherwise I'll close this issue shortly.

**Comment by theimo1221** [comment]
@pmaji "Refreshing of background data" might be misleading.
Yes, the disappearing of tolltip happens due to refresh of data, but just of data wich are on server.
The serverside refreshing of data happens in a different interval and thread.

So as it can be seen in the time in graph title not every "refresh" really grants new data for that particular graph.

But still, as @pmaji said that´s why we have the freeze Button.

@ccampbell Hope I was able to clear this fopr you.

**Comment by ccampbell** [comment]
That is fine, but I think it is a pretty poor user experience that it doesn’t actually stay up long enough for you to read it. What you could do is render the tooltip in the body of the document instead of inside the content that is refreshed. That way it can be absolutely positioned and if a refresh happens and your mouse is still over the dot you can keep the tooltip up but update the contents to match the new dot.

**Comment by theimo1221** [comment]
We are using plotly with dash for rendering so we can't "just render it to body"

If we would prepare all those data on our own I would totally agree with you but this way it's not that easy.

**Comment by ccampbell** [comment]
Aha. That makes sense. Thanks.

One other idea. You could capture the data about the hover and then trigger it programmatically after the refresh. I found this

https://plot.ly/javascript/hover-events/#triggering-hover-events

Obviously, not super high priority. Thanks for your work on this :smile:

**Comment by theimo1221** [comment]
@ccampbell Good idea but there is another misconception. We are using Plotly/ Dash in Python. And having a programmatic callback would result in e.g. you clicking and I get same tooltip.

So we have no single callback except data refresh.
Cause I don´t want to interfere with your Website visit and you not with mine....

As @pmaji mentioned, just freeze/ unfreeze site
