### ISSUE TITLE
Time Stamping - Alt Coin Buzz

### ISSUE THREAD

**Issue by MarkyVee** [pmaji/crypto-whale-watching-app#99]
You guys have a great tool here! I haven't seen any work lately. I'd like to promote you on my segments that I do on Alt Coin Buzz. It's a TA segment along with the news. Are you still working on this? If so can I promote, or would it be better to wait?

Also wondering if you guys are working on a time stamp for the trades to be included in the roll-over. Certainly would be helpful to see if the larger orders are set up to affect the price. 

Thank you in advance!

**Comment by pmaji** [comment]
Hey @MarkyVee! Thanks for reaching out. Definitely still an active project, just a slow period as of late because we're coming off the cliff of a lot of major updates. Let's talk more. Can you reach out to me via telegram (username @pmaji -- same as my GitHub)? I can give you any details you need, answer your questions, etc.
